import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const firaCode = localFont({
  src: [
    {
      path: "../../public/fira-code-2/FiraCode-Regular.ttf", // Adjusted path
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-firaCode",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
